### ISSUE TITLE
The black pre-commit check is failing

### ISSUE THREAD

**Issue by elopio** [flashbots/mev-inspect-py#127]
I merged my branch with main, and it failed with:

```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repop1aprewi/py_env-python3.9/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/runner/.cache/pre-commit/repop1aprewi/py_env-python3.9/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
    from typed_ast import ast3, ast27
  File "/home/runner/.cache/pre-commit/repop1aprewi/py_env-python3.9/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: /home/runner/.cache/pre-commit/repop1aprewi/py_env-python3.9/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
```

https://github.com/flashbots/mev-inspect-py/runs/4181093494

I cannot reproduce this locally.

**Comment by gheise** [comment]
It is likely this arises due to a mismatch between the versions of black and python, updating black might solve this
