### ISSUE TITLE
Failed to create objects from block: 13850154

### ISSUE THREAD

**Issue by soloblack** [flashbots/mev-inspect-py#182]
INFO:__main__:Latest block: 13852901
INFO:__main__:Last written block: 13850153
INFO:__main__:Writing block: 13850154
WARNING:mev_inspect.block:Failed to create objects from block: 13850154: 'result', retrying: 1 / 3
ERROR:__main__:{'code': -32602, 'message': 'Invalid params: invalid type: integer `1`, expected a 0x-prefixed hex string with length between (0; 64].'}
Traceback (most recent call last):
  File "/app/mev_inspect/block.py", line 54, in _fetch_block
    Receipt(**receipt) for receipt in receipts_json["result"]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/listener.py", line 92, in <module>
    run()
  File "/app/mev_inspect/concurrency.py", line 18, in wrapper
    loop.run_until_complete(f(*args, **kwargs))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/listener.py", line 44, in run
    await inspect_next_block(
  File "/app/listener.py", line 75, in inspect_next_block
    await inspector.inspect_single_block(block=block_number)
  File "/app/mev_inspect/inspector.py", line 44, in inspect_single_block
    return await inspect_block(
  File "/app/mev_inspect/inspect_block.py", line 65, in inspect_block
    await inspect_many_blocks(
  File "/app/mev_inspect/inspect_block.py", line 102, in inspect_many_blocks
    block = await create_from_block_number(
  File "/app/mev_inspect/block.py", line 38, in create_from_block_number
    block = await _fetch_block(w3, base_provider, block_number)
  File "/app/mev_inspect/block.py", line 63, in _fetch_block
    return await _fetch_block(w3, base_provider, block_number, retries)
  File "/app/mev_inspect/fees.py", line 5, in fetch_base_fee_per_gas
    base_fees = await w3.eth.fee_history(1, block_number)
  File "/usr/local/lib/python3.9/site-packages/web3/eth.py", line 266, in fee_history
    return await self._fee_history(  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 72, in caller
    result = await w3.manager.coro_request(method_str,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 203, in coro_request
    return self.formatted_response(response,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32602, 'message': 'Invalid params: invalid type: integer `1`, expected a 0x-prefixed hex string with length between (0; 64].'}

but when i run ' ./mev inspect 13850154 ', it is fine.

**Comment by soloblack** [comment]
sorry i solve that.

**Comment by 0xJchen** [comment]
> sorry i solve that.

Hi ser how do you solved this?
